baseURL: http://example.org/
languageCode: zh-cn
title: _rqy 的博客
newContentEditor: emacs

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

security:
  exec:
    osEnv: ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME|SSH_AUTH_SOCK|USERPROFILE|XDG_CONFIG_HOME|HTTP_PROXY|HTTPS_PROXY)$']

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    homeInfoParams:
      Title: _rqy 的博客!
      Content: 喵喵喵

    socialIcons: # optional
      - name: "email"
        url: "mailto:renqy20@qq.com"
      - name: "github"
        url: "https://github.com/rqy1458814497"
      - name: "bilibili"
        url: "https://space.bilibili.com/76936471"
      - name: "stackoverflow"
        url: "https://stackoverflow.com/users/19916817/rqy"

    DateFormat: 2006 年 1 月 2 日
    defaultTheme: auto
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: archive
      name: 归档
      url: /archive/
      weight: 30
    - identifier: search
      name: 搜索
      url: /search/
      weight: 100
